import localFont from 'next/font/local'
import './globals.css'
import { Poppins } from 'next/font/google'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})
const poppins = Poppins({
  subsets: ['latin'], // choose the appropriate subset
  weight: ['400', '700'], // adjust weights as needed
})

export const metadata = {
  title: 'Chartered',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${poppins.className} `}
      >
        {children}
      </body>
    </html>
  )
}
